<a href="https://colab.research.google.com/github/GreatNaza/Deep-Learning-Algorithm-for-Enhance-Geothermal-Systems/blob/main/Python_For_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [ ]:
import numpy as np


In [ ]:
arr =[1,2,3,4,4,4]
a = np.array(arr)

In [ ]:
type(a)
print(a.shape)

(6,)


In [ ]:
print(a.ndim)

1


In [ ]:
Matrix_B = np.array([[1,2,-4],[2,3,6],[1,8,-6]])

In [ ]:
Matrix_B.ndim

2

In [ ]:
Matrix_B

array([[ 1,  2, -4],
       [ 2,  3,  6],
       [ 1,  8, -6]])

In [ ]:
Matrix_B.shape

(3, 3)

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.identity((2))

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.diagonal(Matrix_B)

array([ 1,  3, -6])

In [ ]:
np.random.random(2,3)